version: '3.8'

services:
  app:
    image: node:18
    container_name: MNJ
    ports:
      - "6060:6060"
    volumes:
      - "/User"
    environment:
      - PORT=6060
    restart: unless-stopped

